### ISSUE TITLE
not an object or array

### ISSUE THREAD

**Issue by breadpanz** [dimaskiddo/go-whatsapp-cli#1]
https://github.com/dimaskiddo/go-whatsapp-cli/blob/f6da68216c7f7374ab594987c35e0b96a8eb9dad/helper/h_cmd.go#L100

sample request

    {
      "command": "request",
      "message": "Example:",
      "curl": {
        "url": "https://httpbin.org/post",
        "form": ["key1=value1","key2=value2"]
      }
    },

**Comment by breadpanz** [comment]
Issue fixed
change the line to:
`forms, err := cmd.Path("curl.form").Children() `

**Comment by dimaskiddo** [comment]
Just fix it in current release, thanks for checking it 😄
