### ISSUE TITLE
stuck 

### ISSUE THREAD

**Issue by the-jojo-jj** [dimaskiddo/go-whatsapp-cli#4]
Hi, I think I found a bug, or maybe I lost something?

% go run cmd/main/main.go daemon
INFO[2020-10-18T15:08:46+07:00] whatsapp version 2.2035.15
INFO[2020-10-18T15:08:46+07:00] starting communication with whatsapp
INFO[2020-10-18T15:08:48+07:00] logged in to whatsapp as 44744723xxxx

and stuck, not respond with hi message.

**Comment by dimaskiddo** [comment]
it's not stuck it's waiting for a call using a tag (bot's need tag to understand if the call is for the bot)
Please read the source code first, i'am sorry currently i can't explain publicly the detail
