### ISSUE TITLE
Daemon error

### ISSUE THREAD

**Issue by baddwin** [dimaskiddo/go-whatsapp-cli#5]
I got these errors when running the daemon.

    connection closed unexpetedly, reconnecting after 30 seconds
    error processing data: error decoding binary: could not decode binary: invalid string with tag 174

**Comment by dimaskiddo** [comment]
Hello @baddwin can you try to add some paramters related to the whatsapp client version and using latest client version based on whatsapp web client?

--client-version-major <WA_CLIENT_MAJOR_VERSION> --client-version-minor <WA_CLIENT_MINOR_VERSION> --client-version-build <WA_CLEINT_BUILD_VERSION>

or using environment variables
WHATSAPP_CLIENT_VERSION_MAJOR=<WA_CLIENT_MAJOR_VERSION>
WHATSAPP_CLIENT_VERSION_MINOR=<WA_CLIENT_MINOR_VERSION>
WHATSAPP_CLIENT_VERSION_BUILD=<WA_CLIENT_BUILD_VERSION>

Based on my WhatsApp Web Desktop latest version is:
2.2100.4

**Comment by baddwin** [comment]
Thank you @dimaskiddo, it works.
I close this issue for now.
